// Copyright 2022 Fredrick Allan Grott. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.



import 'package:flutter/material.dart';
import 'package:launch_vscode_settings/presentation/themes/app_brand_seed_colors.dart';
import 'package:material_color_utilities/material_color_utilities.dart';

// Gist: CorePalette.of gets a palette of tones based on wallpaper color
//       CorePalette.contentOf gets a palette of tones based on desktop accent color
//
// Scheme settings that could be used, copied from Flex Seed Scheme package:
//
//   hc light
//     prmary 30
//     secondary 40
//     tertiary 30
//     error 40
//     primaryContainer 95
//     secondaryContainer 95
//     tertiaryContainer 95
//     errorContainer 95
//     surfaceTint 30
//
//    hc dark
//      primary 80
//      secondary 80
//      tertiary 80
//      error 80
//      onPrimary 10
//      onSecondary 10
//      onTertiary 10
//      onError 10
//      primaryContainer 20
//      secondaryContainer 20
//      tertiaryContainer 20
//      errorContainer 20
//      onErrorContainer 90
//      surfaceTint 80
//
// see https://github.com/rydmike/flex_seed_scheme/blob/master/lib/src/flex_tones.dart

// Borrow HC settings from Flex Seed Scheme.
// CorePalette.contentOF is accent color as opposed to android corePalette

final CorePalette appCorePalette = CorePalette.of(primaryBrandKeyColor.value);

final CorePalette appSemanticOneCorePalette =
    CorePalette.of(semanticOneColor.value);

final CorePalette appSemanticTwoCorePalette =
    CorePalette.of(semanticTwoColor.value);

final CorePalette appSemanticThreeCorePalette =
    CorePalette.of(semanticThreeColor.value);

final ColorScheme appLightScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(appCorePalette.primary.get(40)),
  onPrimary: Color(appCorePalette.primary.get(100)),
  primaryContainer: Color(appCorePalette.primary.get(95)),
  onPrimaryContainer: Color(appCorePalette.primary.get(10)),
  secondary: Color(appCorePalette.secondary.get(40)),
  onSecondary: Color(appCorePalette.secondary.get(100)),
  secondaryContainer: Color(appCorePalette.secondary.get(95)),
  onSecondaryContainer: Color(appCorePalette.secondary.get(10)),
  tertiary: Color(appCorePalette.tertiary.get(40)),
  onTertiary: Color(appCorePalette.tertiary.get(100)),
  tertiaryContainer: Color(appCorePalette.tertiary.get(95)),
  onTertiaryContainer: Color(appCorePalette.tertiary.get(10)),
  error: Color(appCorePalette.error.get(40)),
  onError: Color(appCorePalette.error.get(100)),
  errorContainer: Color(appCorePalette.error.get(90)),
  onErrorContainer: Color(appCorePalette.error.get(10)),
  background: Color(appCorePalette.neutral.get(99)),
  onBackground: Color(appCorePalette.neutral.get(10)),
  surface: Color(appCorePalette.neutral.get(99)),
  onSurface: Color(appCorePalette.neutral.get(10)),
  surfaceVariant: Color(appCorePalette.neutralVariant.get(90)),
  onSurfaceVariant: Color(appCorePalette.neutralVariant.get(30)),
  outline: Color(appCorePalette.neutralVariant.get(50)),
  outlineVariant: Color(appCorePalette.neutralVariant.get(80)),
  shadow: Color(appCorePalette.neutral.get(0)),
  scrim: Color(appCorePalette.neutral.get(0)),
  inverseSurface: Color(appCorePalette.neutral.get(20)),
  onInverseSurface: Color(appCorePalette.neutral.get(95)),
  inversePrimary: Color(appCorePalette.primary.get(80)),
  surfaceTint: Color(appCorePalette.primary.get(40)),
);

final ColorScheme appLightHCScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(appCorePalette.primary.get(30)),
  onPrimary: Color(appCorePalette.primary.get(100)),
  primaryContainer: Color(appCorePalette.primary.get(90)),
  onPrimaryContainer: Color(appCorePalette.primary.get(10)),
  secondary: Color(appCorePalette.secondary.get(40)),
  onSecondary: Color(appCorePalette.secondary.get(100)),
  secondaryContainer: Color(appCorePalette.secondary.get(90)),
  onSecondaryContainer: Color(appCorePalette.secondary.get(10)),
  tertiary: Color(appCorePalette.tertiary.get(30)),
  onTertiary: Color(appCorePalette.tertiary.get(100)),
  tertiaryContainer: Color(appCorePalette.tertiary.get(90)),
  onTertiaryContainer: Color(appCorePalette.tertiary.get(10)),
  error: Color(appCorePalette.error.get(40)),
  onError: Color(appCorePalette.error.get(100)),
  errorContainer: Color(appCorePalette.error.get(95)),
  onErrorContainer: Color(appCorePalette.error.get(10)),
  background: Color(appCorePalette.neutral.get(99)),
  onBackground: Color(appCorePalette.neutral.get(10)),
  surface: Color(appCorePalette.neutral.get(99)),
  onSurface: Color(appCorePalette.neutral.get(10)),
  surfaceVariant: Color(appCorePalette.neutralVariant.get(90)),
  onSurfaceVariant: Color(appCorePalette.neutralVariant.get(30)),
  outline: Color(appCorePalette.neutralVariant.get(50)),
  outlineVariant: Color(appCorePalette.neutralVariant.get(80)),
  shadow: Color(appCorePalette.neutral.get(0)),
  scrim: Color(appCorePalette.neutral.get(0)),
  inverseSurface: Color(appCorePalette.neutral.get(20)),
  onInverseSurface: Color(appCorePalette.neutral.get(95)),
  inversePrimary: Color(appCorePalette.primary.get(80)),
  surfaceTint: Color(appCorePalette.primary.get(30)),
);

final ColorScheme appDarkScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(appCorePalette.primary.get(80)),
  onPrimary: Color(appCorePalette.primary.get(20)),
  primaryContainer: Color(appCorePalette.primary.get(30)),
  onPrimaryContainer: Color(appCorePalette.primary.get(90)),
  secondary: Color(appCorePalette.secondary.get(80)),
  onSecondary: Color(appCorePalette.secondary.get(20)),
  secondaryContainer: Color(appCorePalette.secondary.get(30)),
  onSecondaryContainer: Color(appCorePalette.secondary.get(90)),
  tertiary: Color(appCorePalette.tertiary.get(80)),
  onTertiary: Color(appCorePalette.tertiary.get(20)),
  tertiaryContainer: Color(appCorePalette.tertiary.get(30)),
  onTertiaryContainer: Color(appCorePalette.tertiary.get(90)),
  error: Color(appCorePalette.error.get(80)),
  onError: Color(appCorePalette.error.get(20)),
  errorContainer: Color(appCorePalette.error.get(30)),
  onErrorContainer: Color(appCorePalette.error.get(90)),
  background: Color(appCorePalette.neutral.get(10)),
  onBackground: Color(appCorePalette.neutral.get(90)),
  surface: Color(appCorePalette.neutral.get(10)),
  onSurface: Color(appCorePalette.neutral.get(90)),
  surfaceVariant: Color(appCorePalette.neutralVariant.get(30)),
  onSurfaceVariant: Color(appCorePalette.neutralVariant.get(80)),
  outline: Color(appCorePalette.neutralVariant.get(60)),
  outlineVariant: Color(appCorePalette.neutralVariant.get(30)),
  shadow: Color(appCorePalette.neutral.get(0)),
  scrim: Color(appCorePalette.neutral.get(0)),
  inverseSurface: Color(appCorePalette.neutral.get(90)),
  onInverseSurface: Color(appCorePalette.neutral.get(20)),
  inversePrimary: Color(appCorePalette.primary.get(40)),
  surfaceTint: Color(appCorePalette.primary.get(80)),
);

final ColorScheme appDarkHCScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(appCorePalette.primary.get(80)),
  onPrimary: Color(appCorePalette.primary.get(10)),
  primaryContainer: Color(appCorePalette.primary.get(20)),
  onPrimaryContainer: Color(appCorePalette.primary.get(90)),
  secondary: Color(appCorePalette.secondary.get(80)),
  onSecondary: Color(appCorePalette.secondary.get(10)),
  secondaryContainer: Color(appCorePalette.secondary.get(20)),
  onSecondaryContainer: Color(appCorePalette.secondary.get(90)),
  tertiary: Color(appCorePalette.tertiary.get(80)),
  onTertiary: Color(appCorePalette.tertiary.get(10)),
  tertiaryContainer: Color(appCorePalette.tertiary.get(20)),
  onTertiaryContainer: Color(appCorePalette.tertiary.get(90)),
  error: Color(appCorePalette.error.get(80)),
  onError: Color(appCorePalette.error.get(10)),
  errorContainer: Color(appCorePalette.error.get(20)),
  onErrorContainer: Color(appCorePalette.error.get(80)),
  background: Color(appCorePalette.neutral.get(10)),
  onBackground: Color(appCorePalette.neutral.get(90)),
  surface: Color(appCorePalette.neutral.get(10)),
  onSurface: Color(appCorePalette.neutral.get(90)),
  surfaceVariant: Color(appCorePalette.neutralVariant.get(30)),
  onSurfaceVariant: Color(appCorePalette.neutralVariant.get(80)),
  outline: Color(appCorePalette.neutralVariant.get(60)),
  outlineVariant: Color(appCorePalette.neutralVariant.get(30)),
  shadow: Color(appCorePalette.neutral.get(0)),
  scrim: Color(appCorePalette.neutral.get(0)),
  inverseSurface: Color(appCorePalette.neutral.get(90)),
  onInverseSurface: Color(appCorePalette.neutral.get(20)),
  inversePrimary: Color(appCorePalette.primary.get(40)),
  surfaceTint: Color(appCorePalette.primary.get(80)),
);

final ColorScheme appLightSemanticOneScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(appSemanticOneCorePalette.primary.get(40)),
  onPrimary: Color(appSemanticOneCorePalette.primary.get(100)),
  primaryContainer: Color(appSemanticOneCorePalette.primary.get(95)),
  onPrimaryContainer: Color(appSemanticOneCorePalette.primary.get(10)),
  secondary: Color(appSemanticOneCorePalette.secondary.get(40)),
  onSecondary: Color(appSemanticOneCorePalette.secondary.get(100)),
  secondaryContainer: Color(appSemanticOneCorePalette.secondary.get(95)),
  onSecondaryContainer: Color(appSemanticOneCorePalette.secondary.get(10)),
  tertiary: Color(appSemanticOneCorePalette.tertiary.get(40)),
  onTertiary: Color(appSemanticOneCorePalette.tertiary.get(100)),
  tertiaryContainer: Color(appSemanticOneCorePalette.tertiary.get(95)),
  onTertiaryContainer: Color(appSemanticOneCorePalette.tertiary.get(10)),
  error: Color(appSemanticOneCorePalette.error.get(40)),
  onError: Color(appSemanticOneCorePalette.error.get(100)),
  errorContainer: Color(appSemanticOneCorePalette.error.get(90)),
  onErrorContainer: Color(appSemanticOneCorePalette.error.get(10)),
  background: Color(appSemanticOneCorePalette.neutral.get(99)),
  onBackground: Color(appSemanticOneCorePalette.neutral.get(10)),
  surface: Color(appSemanticOneCorePalette.neutral.get(99)),
  onSurface: Color(appSemanticOneCorePalette.neutral.get(10)),
  surfaceVariant: Color(appSemanticOneCorePalette.neutralVariant.get(90)),
  onSurfaceVariant: Color(appSemanticOneCorePalette.neutralVariant.get(30)),
  outline: Color(appSemanticOneCorePalette.neutralVariant.get(50)),
  outlineVariant: Color(appSemanticOneCorePalette.neutralVariant.get(80)),
  shadow: Color(appSemanticOneCorePalette.neutral.get(0)),
  scrim: Color(appSemanticOneCorePalette.neutral.get(0)),
  inverseSurface: Color(appSemanticOneCorePalette.neutral.get(20)),
  onInverseSurface: Color(appSemanticOneCorePalette.neutral.get(95)),
  inversePrimary: Color(appSemanticOneCorePalette.primary.get(80)),
  surfaceTint: Color(appSemanticOneCorePalette.primary.get(40)),
);

final ColorScheme appLightHCSemanticOneScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(appSemanticOneCorePalette.primary.get(30)),
  onPrimary: Color(appSemanticOneCorePalette.primary.get(100)),
  primaryContainer: Color(appSemanticOneCorePalette.primary.get(90)),
  onPrimaryContainer: Color(appSemanticOneCorePalette.primary.get(10)),
  secondary: Color(appSemanticOneCorePalette.secondary.get(40)),
  onSecondary: Color(appSemanticOneCorePalette.secondary.get(100)),
  secondaryContainer: Color(appSemanticOneCorePalette.secondary.get(90)),
  onSecondaryContainer: Color(appSemanticOneCorePalette.secondary.get(10)),
  tertiary: Color(appSemanticOneCorePalette.tertiary.get(30)),
  onTertiary: Color(appSemanticOneCorePalette.tertiary.get(100)),
  tertiaryContainer: Color(appSemanticOneCorePalette.tertiary.get(90)),
  onTertiaryContainer: Color(appSemanticOneCorePalette.tertiary.get(10)),
  error: Color(appSemanticOneCorePalette.error.get(40)),
  onError: Color(appSemanticOneCorePalette.error.get(100)),
  errorContainer: Color(appSemanticOneCorePalette.error.get(95)),
  onErrorContainer: Color(appSemanticOneCorePalette.error.get(10)),
  background: Color(appSemanticOneCorePalette.neutral.get(99)),
  onBackground: Color(appSemanticOneCorePalette.neutral.get(10)),
  surface: Color(appSemanticOneCorePalette.neutral.get(99)),
  onSurface: Color(appSemanticOneCorePalette.neutral.get(10)),
  surfaceVariant: Color(appSemanticOneCorePalette.neutralVariant.get(90)),
  onSurfaceVariant: Color(appSemanticOneCorePalette.neutralVariant.get(30)),
  outline: Color(appSemanticOneCorePalette.neutralVariant.get(50)),
  outlineVariant: Color(appSemanticOneCorePalette.neutralVariant.get(80)),
  shadow: Color(appSemanticOneCorePalette.neutral.get(0)),
  scrim: Color(appSemanticOneCorePalette.neutral.get(0)),
  inverseSurface: Color(appSemanticOneCorePalette.neutral.get(20)),
  onInverseSurface: Color(appSemanticOneCorePalette.neutral.get(95)),
  inversePrimary: Color(appSemanticOneCorePalette.primary.get(80)),
  surfaceTint: Color(appSemanticOneCorePalette.primary.get(30)),
);

final ColorScheme appDarkSemanticOneScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(appSemanticOneCorePalette.primary.get(80)),
  onPrimary: Color(appSemanticOneCorePalette.primary.get(20)),
  primaryContainer: Color(appSemanticOneCorePalette.primary.get(30)),
  onPrimaryContainer: Color(appSemanticOneCorePalette.primary.get(90)),
  secondary: Color(appSemanticOneCorePalette.secondary.get(80)),
  onSecondary: Color(appSemanticOneCorePalette.secondary.get(20)),
  secondaryContainer: Color(appSemanticOneCorePalette.secondary.get(30)),
  onSecondaryContainer: Color(appSemanticOneCorePalette.secondary.get(90)),
  tertiary: Color(appSemanticOneCorePalette.tertiary.get(80)),
  onTertiary: Color(appSemanticOneCorePalette.tertiary.get(20)),
  tertiaryContainer: Color(appSemanticOneCorePalette.tertiary.get(30)),
  onTertiaryContainer: Color(appSemanticOneCorePalette.tertiary.get(90)),
  error: Color(appSemanticOneCorePalette.error.get(80)),
  onError: Color(appSemanticOneCorePalette.error.get(20)),
  errorContainer: Color(appSemanticOneCorePalette.error.get(30)),
  onErrorContainer: Color(appSemanticOneCorePalette.error.get(90)),
  background: Color(appSemanticOneCorePalette.neutral.get(10)),
  onBackground: Color(appSemanticOneCorePalette.neutral.get(90)),
  surface: Color(appSemanticOneCorePalette.neutral.get(10)),
  onSurface: Color(appSemanticOneCorePalette.neutral.get(90)),
  surfaceVariant: Color(appSemanticOneCorePalette.neutralVariant.get(30)),
  onSurfaceVariant: Color(appSemanticOneCorePalette.neutralVariant.get(80)),
  outline: Color(appSemanticOneCorePalette.neutralVariant.get(60)),
  outlineVariant: Color(appSemanticOneCorePalette.neutralVariant.get(30)),
  shadow: Color(appSemanticOneCorePalette.neutral.get(0)),
  scrim: Color(appSemanticOneCorePalette.neutral.get(0)),
  inverseSurface: Color(appSemanticOneCorePalette.neutral.get(90)),
  onInverseSurface: Color(appSemanticOneCorePalette.neutral.get(20)),
  inversePrimary: Color(appSemanticOneCorePalette.primary.get(40)),
  surfaceTint: Color(appSemanticOneCorePalette.primary.get(80)),
);

final ColorScheme appDarkHCSemanticOneScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(appSemanticOneCorePalette.primary.get(80)),
  onPrimary: Color(appSemanticOneCorePalette.primary.get(10)),
  primaryContainer: Color(appSemanticOneCorePalette.primary.get(20)),
  onPrimaryContainer: Color(appSemanticOneCorePalette.primary.get(90)),
  secondary: Color(appSemanticOneCorePalette.secondary.get(80)),
  onSecondary: Color(appSemanticOneCorePalette.secondary.get(10)),
  secondaryContainer: Color(appSemanticOneCorePalette.secondary.get(20)),
  onSecondaryContainer: Color(appSemanticOneCorePalette.secondary.get(90)),
  tertiary: Color(appSemanticOneCorePalette.tertiary.get(80)),
  onTertiary: Color(appSemanticOneCorePalette.tertiary.get(10)),
  tertiaryContainer: Color(appSemanticOneCorePalette.tertiary.get(20)),
  onTertiaryContainer: Color(appSemanticOneCorePalette.tertiary.get(90)),
  error: Color(appSemanticOneCorePalette.error.get(80)),
  onError: Color(appSemanticOneCorePalette.error.get(10)),
  errorContainer: Color(appSemanticOneCorePalette.error.get(20)),
  onErrorContainer: Color(appSemanticOneCorePalette.error.get(80)),
  background: Color(appSemanticOneCorePalette.neutral.get(10)),
  onBackground: Color(appSemanticOneCorePalette.neutral.get(90)),
  surface: Color(appSemanticOneCorePalette.neutral.get(10)),
  onSurface: Color(appSemanticOneCorePalette.neutral.get(90)),
  surfaceVariant: Color(appSemanticOneCorePalette.neutralVariant.get(30)),
  onSurfaceVariant: Color(appSemanticOneCorePalette.neutralVariant.get(80)),
  outline: Color(appSemanticOneCorePalette.neutralVariant.get(60)),
  outlineVariant: Color(appSemanticOneCorePalette.neutralVariant.get(30)),
  shadow: Color(appSemanticOneCorePalette.neutral.get(0)),
  scrim: Color(appSemanticOneCorePalette.neutral.get(0)),
  inverseSurface: Color(appSemanticOneCorePalette.neutral.get(90)),
  onInverseSurface: Color(appSemanticOneCorePalette.neutral.get(20)),
  inversePrimary: Color(appSemanticOneCorePalette.primary.get(40)),
  surfaceTint: Color(appSemanticOneCorePalette.primary.get(80)),
);


final ColorScheme appLightSemanticTwoScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(appSemanticTwoCorePalette.primary.get(40)),
  onPrimary: Color(appSemanticTwoCorePalette.primary.get(100)),
  primaryContainer: Color(appSemanticTwoCorePalette.primary.get(95)),
  onPrimaryContainer: Color(appSemanticTwoCorePalette.primary.get(10)),
  secondary: Color(appSemanticTwoCorePalette.secondary.get(40)),
  onSecondary: Color(appSemanticTwoCorePalette.secondary.get(100)),
  secondaryContainer: Color(appSemanticTwoCorePalette.secondary.get(95)),
  onSecondaryContainer: Color(appSemanticTwoCorePalette.secondary.get(10)),
  tertiary: Color(appSemanticTwoCorePalette.tertiary.get(40)),
  onTertiary: Color(appSemanticTwoCorePalette.tertiary.get(100)),
  tertiaryContainer: Color(appSemanticTwoCorePalette.tertiary.get(95)),
  onTertiaryContainer: Color(appSemanticTwoCorePalette.tertiary.get(10)),
  error: Color(appSemanticTwoCorePalette.error.get(40)),
  onError: Color(appSemanticTwoCorePalette.error.get(100)),
  errorContainer: Color(appSemanticTwoCorePalette.error.get(90)),
  onErrorContainer: Color(appSemanticTwoCorePalette.error.get(10)),
  background: Color(appSemanticTwoCorePalette.neutral.get(99)),
  onBackground: Color(appSemanticTwoCorePalette.neutral.get(10)),
  surface: Color(appSemanticTwoCorePalette.neutral.get(99)),
  onSurface: Color(appSemanticTwoCorePalette.neutral.get(10)),
  surfaceVariant: Color(appSemanticTwoCorePalette.neutralVariant.get(90)),
  onSurfaceVariant: Color(appSemanticTwoCorePalette.neutralVariant.get(30)),
  outline: Color(appSemanticTwoCorePalette.neutralVariant.get(50)),
  outlineVariant: Color(appSemanticTwoCorePalette.neutralVariant.get(80)),
  shadow: Color(appSemanticTwoCorePalette.neutral.get(0)),
  scrim: Color(appSemanticTwoCorePalette.neutral.get(0)),
  inverseSurface: Color(appSemanticTwoCorePalette.neutral.get(20)),
  onInverseSurface: Color(appSemanticTwoCorePalette.neutral.get(95)),
  inversePrimary: Color(appSemanticTwoCorePalette.primary.get(80)),
  surfaceTint: Color(appSemanticTwoCorePalette.primary.get(40)),
);

final ColorScheme appLightHCSemanticTwoScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(appSemanticTwoCorePalette.primary.get(30)),
  onPrimary: Color(appSemanticTwoCorePalette.primary.get(100)),
  primaryContainer: Color(appSemanticTwoCorePalette.primary.get(90)),
  onPrimaryContainer: Color(appSemanticTwoCorePalette.primary.get(10)),
  secondary: Color(appSemanticTwoCorePalette.secondary.get(40)),
  onSecondary: Color(appSemanticTwoCorePalette.secondary.get(100)),
  secondaryContainer: Color(appSemanticTwoCorePalette.secondary.get(90)),
  onSecondaryContainer: Color(appSemanticTwoCorePalette.secondary.get(10)),
  tertiary: Color(appSemanticTwoCorePalette.tertiary.get(30)),
  onTertiary: Color(appSemanticTwoCorePalette.tertiary.get(100)),
  tertiaryContainer: Color(appSemanticTwoCorePalette.tertiary.get(90)),
  onTertiaryContainer: Color(appSemanticTwoCorePalette.tertiary.get(10)),
  error: Color(appSemanticTwoCorePalette.error.get(40)),
  onError: Color(appSemanticTwoCorePalette.error.get(100)),
  errorContainer: Color(appSemanticTwoCorePalette.error.get(95)),
  onErrorContainer: Color(appSemanticTwoCorePalette.error.get(10)),
  background: Color(appSemanticTwoCorePalette.neutral.get(99)),
  onBackground: Color(appSemanticTwoCorePalette.neutral.get(10)),
  surface: Color(appSemanticTwoCorePalette.neutral.get(99)),
  onSurface: Color(appSemanticTwoCorePalette.neutral.get(10)),
  surfaceVariant: Color(appSemanticTwoCorePalette.neutralVariant.get(90)),
  onSurfaceVariant: Color(appSemanticTwoCorePalette.neutralVariant.get(30)),
  outline: Color(appSemanticTwoCorePalette.neutralVariant.get(50)),
  outlineVariant: Color(appSemanticTwoCorePalette.neutralVariant.get(80)),
  shadow: Color(appSemanticTwoCorePalette.neutral.get(0)),
  scrim: Color(appSemanticTwoCorePalette.neutral.get(0)),
  inverseSurface: Color(appSemanticTwoCorePalette.neutral.get(20)),
  onInverseSurface: Color(appSemanticTwoCorePalette.neutral.get(95)),
  inversePrimary: Color(appSemanticTwoCorePalette.primary.get(80)),
  surfaceTint: Color(appSemanticTwoCorePalette.primary.get(30)),
);

final ColorScheme appDarkSemanticTwoScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(appSemanticTwoCorePalette.primary.get(80)),
  onPrimary: Color(appSemanticTwoCorePalette.primary.get(20)),
  primaryContainer: Color(appSemanticTwoCorePalette.primary.get(30)),
  onPrimaryContainer: Color(appSemanticTwoCorePalette.primary.get(90)),
  secondary: Color(appSemanticTwoCorePalette.secondary.get(80)),
  onSecondary: Color(appSemanticTwoCorePalette.secondary.get(20)),
  secondaryContainer: Color(appSemanticTwoCorePalette.secondary.get(30)),
  onSecondaryContainer: Color(appSemanticTwoCorePalette.secondary.get(90)),
  tertiary: Color(appSemanticTwoCorePalette.tertiary.get(80)),
  onTertiary: Color(appSemanticTwoCorePalette.tertiary.get(20)),
  tertiaryContainer: Color(appSemanticTwoCorePalette.tertiary.get(30)),
  onTertiaryContainer: Color(appSemanticTwoCorePalette.tertiary.get(90)),
  error: Color(appSemanticTwoCorePalette.error.get(80)),
  onError: Color(appSemanticTwoCorePalette.error.get(20)),
  errorContainer: Color(appSemanticTwoCorePalette.error.get(30)),
  onErrorContainer: Color(appSemanticTwoCorePalette.error.get(90)),
  background: Color(appSemanticTwoCorePalette.neutral.get(10)),
  onBackground: Color(appSemanticTwoCorePalette.neutral.get(90)),
  surface: Color(appSemanticTwoCorePalette.neutral.get(10)),
  onSurface: Color(appSemanticTwoCorePalette.neutral.get(90)),
  surfaceVariant: Color(appSemanticTwoCorePalette.neutralVariant.get(30)),
  onSurfaceVariant: Color(appSemanticTwoCorePalette.neutralVariant.get(80)),
  outline: Color(appSemanticTwoCorePalette.neutralVariant.get(60)),
  outlineVariant: Color(appSemanticTwoCorePalette.neutralVariant.get(30)),
  shadow: Color(appSemanticTwoCorePalette.neutral.get(0)),
  scrim: Color(appSemanticTwoCorePalette.neutral.get(0)),
  inverseSurface: Color(appSemanticTwoCorePalette.neutral.get(90)),
  onInverseSurface: Color(appSemanticTwoCorePalette.neutral.get(20)),
  inversePrimary: Color(appSemanticTwoCorePalette.primary.get(40)),
  surfaceTint: Color(appSemanticTwoCorePalette.primary.get(80)),
);

final ColorScheme appDarkHCSemanticTwoScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(appSemanticTwoCorePalette.primary.get(80)),
  onPrimary: Color(appSemanticTwoCorePalette.primary.get(10)),
  primaryContainer: Color(appSemanticTwoCorePalette.primary.get(20)),
  onPrimaryContainer: Color(appSemanticTwoCorePalette.primary.get(90)),
  secondary: Color(appSemanticTwoCorePalette.secondary.get(80)),
  onSecondary: Color(appSemanticTwoCorePalette.secondary.get(10)),
  secondaryContainer: Color(appSemanticTwoCorePalette.secondary.get(20)),
  onSecondaryContainer: Color(appSemanticTwoCorePalette.secondary.get(90)),
  tertiary: Color(appSemanticTwoCorePalette.tertiary.get(80)),
  onTertiary: Color(appSemanticTwoCorePalette.tertiary.get(10)),
  tertiaryContainer: Color(appSemanticTwoCorePalette.tertiary.get(20)),
  onTertiaryContainer: Color(appSemanticTwoCorePalette.tertiary.get(90)),
  error: Color(appSemanticTwoCorePalette.error.get(80)),
  onError: Color(appSemanticTwoCorePalette.error.get(10)),
  errorContainer: Color(appSemanticTwoCorePalette.error.get(20)),
  onErrorContainer: Color(appSemanticTwoCorePalette.error.get(80)),
  background: Color(appSemanticTwoCorePalette.neutral.get(10)),
  onBackground: Color(appSemanticTwoCorePalette.neutral.get(90)),
  surface: Color(appSemanticTwoCorePalette.neutral.get(10)),
  onSurface: Color(appSemanticTwoCorePalette.neutral.get(90)),
  surfaceVariant: Color(appSemanticTwoCorePalette.neutralVariant.get(30)),
  onSurfaceVariant: Color(appSemanticTwoCorePalette.neutralVariant.get(80)),
  outline: Color(appSemanticTwoCorePalette.neutralVariant.get(60)),
  outlineVariant: Color(appSemanticTwoCorePalette.neutralVariant.get(30)),
  shadow: Color(appSemanticTwoCorePalette.neutral.get(0)),
  scrim: Color(appSemanticTwoCorePalette.neutral.get(0)),
  inverseSurface: Color(appSemanticTwoCorePalette.neutral.get(90)),
  onInverseSurface: Color(appSemanticTwoCorePalette.neutral.get(20)),
  inversePrimary: Color(appSemanticTwoCorePalette.primary.get(40)),
  surfaceTint: Color(appSemanticTwoCorePalette.primary.get(80)),
);

final ColorScheme appLightSemanticThreeScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(appSemanticThreeCorePalette.primary.get(40)),
  onPrimary: Color(appSemanticThreeCorePalette.primary.get(100)),
  primaryContainer: Color(appSemanticThreeCorePalette.primary.get(95)),
  onPrimaryContainer: Color(appSemanticThreeCorePalette.primary.get(10)),
  secondary: Color(appSemanticThreeCorePalette.secondary.get(40)),
  onSecondary: Color(appSemanticThreeCorePalette.secondary.get(100)),
  secondaryContainer: Color(appSemanticThreeCorePalette.secondary.get(95)),
  onSecondaryContainer: Color(appSemanticThreeCorePalette.secondary.get(10)),
  tertiary: Color(appSemanticThreeCorePalette.tertiary.get(40)),
  onTertiary: Color(appSemanticThreeCorePalette.tertiary.get(100)),
  tertiaryContainer: Color(appSemanticThreeCorePalette.tertiary.get(95)),
  onTertiaryContainer: Color(appSemanticThreeCorePalette.tertiary.get(10)),
  error: Color(appSemanticThreeCorePalette.error.get(40)),
  onError: Color(appSemanticThreeCorePalette.error.get(100)),
  errorContainer: Color(appSemanticThreeCorePalette.error.get(90)),
  onErrorContainer: Color(appSemanticThreeCorePalette.error.get(10)),
  background: Color(appSemanticThreeCorePalette.neutral.get(99)),
  onBackground: Color(appSemanticThreeCorePalette.neutral.get(10)),
  surface: Color(appSemanticThreeCorePalette.neutral.get(99)),
  onSurface: Color(appSemanticThreeCorePalette.neutral.get(10)),
  surfaceVariant: Color(appSemanticThreeCorePalette.neutralVariant.get(90)),
  onSurfaceVariant: Color(appSemanticThreeCorePalette.neutralVariant.get(30)),
  outline: Color(appSemanticThreeCorePalette.neutralVariant.get(50)),
  outlineVariant: Color(appSemanticThreeCorePalette.neutralVariant.get(80)),
  shadow: Color(appSemanticThreeCorePalette.neutral.get(0)),
  scrim: Color(appSemanticThreeCorePalette.neutral.get(0)),
  inverseSurface: Color(appSemanticThreeCorePalette.neutral.get(20)),
  onInverseSurface: Color(appSemanticThreeCorePalette.neutral.get(95)),
  inversePrimary: Color(appSemanticThreeCorePalette.primary.get(80)),
  surfaceTint: Color(appSemanticThreeCorePalette.primary.get(40)),
);

final ColorScheme appLightHCSemanticThreeScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(appSemanticThreeCorePalette.primary.get(30)),
  onPrimary: Color(appSemanticThreeCorePalette.primary.get(100)),
  primaryContainer: Color(appSemanticThreeCorePalette.primary.get(90)),
  onPrimaryContainer: Color(appSemanticThreeCorePalette.primary.get(10)),
  secondary: Color(appSemanticThreeCorePalette.secondary.get(40)),
  onSecondary: Color(appSemanticThreeCorePalette.secondary.get(100)),
  secondaryContainer: Color(appSemanticThreeCorePalette.secondary.get(90)),
  onSecondaryContainer: Color(appSemanticThreeCorePalette.secondary.get(10)),
  tertiary: Color(appSemanticThreeCorePalette.tertiary.get(30)),
  onTertiary: Color(appSemanticThreeCorePalette.tertiary.get(100)),
  tertiaryContainer: Color(appSemanticThreeCorePalette.tertiary.get(90)),
  onTertiaryContainer: Color(appSemanticThreeCorePalette.tertiary.get(10)),
  error: Color(appSemanticThreeCorePalette.error.get(40)),
  onError: Color(appSemanticThreeCorePalette.error.get(100)),
  errorContainer: Color(appSemanticThreeCorePalette.error.get(95)),
  onErrorContainer: Color(appSemanticThreeCorePalette.error.get(10)),
  background: Color(appSemanticThreeCorePalette.neutral.get(99)),
  onBackground: Color(appSemanticThreeCorePalette.neutral.get(10)),
  surface: Color(appSemanticThreeCorePalette.neutral.get(99)),
  onSurface: Color(appSemanticThreeCorePalette.neutral.get(10)),
  surfaceVariant: Color(appSemanticThreeCorePalette.neutralVariant.get(90)),
  onSurfaceVariant: Color(appSemanticThreeCorePalette.neutralVariant.get(30)),
  outline: Color(appSemanticThreeCorePalette.neutralVariant.get(50)),
  outlineVariant: Color(appSemanticThreeCorePalette.neutralVariant.get(80)),
  shadow: Color(appSemanticThreeCorePalette.neutral.get(0)),
  scrim: Color(appSemanticThreeCorePalette.neutral.get(0)),
  inverseSurface: Color(appSemanticThreeCorePalette.neutral.get(20)),
  onInverseSurface: Color(appSemanticThreeCorePalette.neutral.get(95)),
  inversePrimary: Color(appSemanticThreeCorePalette.primary.get(80)),
  surfaceTint: Color(appSemanticThreeCorePalette.primary.get(30)),
);

final ColorScheme appDarkSemanticThreeScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(appSemanticThreeCorePalette.primary.get(80)),
  onPrimary: Color(appSemanticThreeCorePalette.primary.get(20)),
  primaryContainer: Color(appSemanticThreeCorePalette.primary.get(30)),
  onPrimaryContainer: Color(appSemanticThreeCorePalette.primary.get(90)),
  secondary: Color(appSemanticThreeCorePalette.secondary.get(80)),
  onSecondary: Color(appSemanticThreeCorePalette.secondary.get(20)),
  secondaryContainer: Color(appSemanticThreeCorePalette.secondary.get(30)),
  onSecondaryContainer: Color(appSemanticThreeCorePalette.secondary.get(90)),
  tertiary: Color(appSemanticThreeCorePalette.tertiary.get(80)),
  onTertiary: Color(appSemanticThreeCorePalette.tertiary.get(20)),
  tertiaryContainer: Color(appSemanticThreeCorePalette.tertiary.get(30)),
  onTertiaryContainer: Color(appSemanticThreeCorePalette.tertiary.get(90)),
  error: Color(appSemanticThreeCorePalette.error.get(80)),
  onError: Color(appSemanticThreeCorePalette.error.get(20)),
  errorContainer: Color(appSemanticThreeCorePalette.error.get(30)),
  onErrorContainer: Color(appSemanticThreeCorePalette.error.get(90)),
  background: Color(appSemanticThreeCorePalette.neutral.get(10)),
  onBackground: Color(appSemanticThreeCorePalette.neutral.get(90)),
  surface: Color(appSemanticThreeCorePalette.neutral.get(10)),
  onSurface: Color(appSemanticThreeCorePalette.neutral.get(90)),
  surfaceVariant: Color(appSemanticThreeCorePalette.neutralVariant.get(30)),
  onSurfaceVariant: Color(appSemanticThreeCorePalette.neutralVariant.get(80)),
  outline: Color(appSemanticThreeCorePalette.neutralVariant.get(60)),
  outlineVariant: Color(appSemanticThreeCorePalette.neutralVariant.get(30)),
  shadow: Color(appSemanticThreeCorePalette.neutral.get(0)),
  scrim: Color(appSemanticThreeCorePalette.neutral.get(0)),
  inverseSurface: Color(appSemanticThreeCorePalette.neutral.get(90)),
  onInverseSurface: Color(appSemanticThreeCorePalette.neutral.get(20)),
  inversePrimary: Color(appSemanticThreeCorePalette.primary.get(40)),
  surfaceTint: Color(appSemanticThreeCorePalette.primary.get(80)),
);

final ColorScheme appDarkHCSemanticThreeScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(appSemanticThreeCorePalette.primary.get(80)),
  onPrimary: Color(appSemanticThreeCorePalette.primary.get(10)),
  primaryContainer: Color(appSemanticThreeCorePalette.primary.get(20)),
  onPrimaryContainer: Color(appSemanticThreeCorePalette.primary.get(90)),
  secondary: Color(appSemanticThreeCorePalette.secondary.get(80)),
  onSecondary: Color(appSemanticThreeCorePalette.secondary.get(10)),
  secondaryContainer: Color(appSemanticThreeCorePalette.secondary.get(20)),
  onSecondaryContainer: Color(appSemanticThreeCorePalette.secondary.get(90)),
  tertiary: Color(appSemanticThreeCorePalette.tertiary.get(80)),
  onTertiary: Color(appSemanticThreeCorePalette.tertiary.get(10)),
  tertiaryContainer: Color(appSemanticThreeCorePalette.tertiary.get(20)),
  onTertiaryContainer: Color(appSemanticThreeCorePalette.tertiary.get(90)),
  error: Color(appSemanticThreeCorePalette.error.get(80)),
  onError: Color(appSemanticThreeCorePalette.error.get(10)),
  errorContainer: Color(appSemanticThreeCorePalette.error.get(20)),
  onErrorContainer: Color(appSemanticThreeCorePalette.error.get(80)),
  background: Color(appSemanticThreeCorePalette.neutral.get(10)),
  onBackground: Color(appSemanticThreeCorePalette.neutral.get(90)),
  surface: Color(appSemanticThreeCorePalette.neutral.get(10)),
  onSurface: Color(appSemanticThreeCorePalette.neutral.get(90)),
  surfaceVariant: Color(appSemanticThreeCorePalette.neutralVariant.get(30)),
  onSurfaceVariant: Color(appSemanticThreeCorePalette.neutralVariant.get(80)),
  outline: Color(appSemanticThreeCorePalette.neutralVariant.get(60)),
  outlineVariant: Color(appSemanticThreeCorePalette.neutralVariant.get(30)),
  shadow: Color(appSemanticThreeCorePalette.neutral.get(0)),
  scrim: Color(appSemanticThreeCorePalette.neutral.get(0)),
  inverseSurface: Color(appSemanticThreeCorePalette.neutral.get(90)),
  onInverseSurface: Color(appSemanticThreeCorePalette.neutral.get(20)),
  inversePrimary: Color(appSemanticThreeCorePalette.primary.get(40)),
  surfaceTint: Color(appSemanticThreeCorePalette.primary.get(80)),
);
